### PR TITLE
Include level 3 headings in sidebar

### LINKED ISSUE #69: Include sub-sections in navigation side menu
In sandpaper, lesson html have episodes on the side bar which shows only main sections on uncollapsing.

Is there any way we can also see subsections as well?

### PR DESCRIPTION
**Pull request by milanmlft**
Adds level 3 subheadings to the navigation sidebar and allows clicking them to scroll to the corresponding section.

To test locally, run

```r
remotes::install_github("LearnToDiscover/sandpaper@milanmlft/sidebar-subheadings")
sandpaper::build_lesson("/path/to/lesson/")
```

in R where `"/path/to/lesson"` is the path to any lesson directory you have locally (preferably one with level 3 headings to see what changed :slightly_smiling_face:), `Basic_Python` is probably a good test case

Fixes #69

### CODE REVIEW

**Review by sabaferdous12 — CHANGES_REQUESTED** [review]
Hi Milan, 

Thank you for this update. It looks good but Adam and I discussed and we think, is there a way that these subsections are collapsible as they can overwhelm the interface for people may be. What do you think?

**Comment by milanmlft** [comment]
> is there a way that these subsections are collapsible as they can overwhelm the interface for people may be. What do you think?

I think this might be possible but would require significantly more work. So maybe I'd suggest creating a new issue for that and get this PR merged in?

**Comment by sabaferdous12** [comment]
@milan, do I still need to create a new issue for this extension and approve this for a merge as it is?

**Review by sabaferdous12 — APPROVED** [review]

**Comment by milanmlft** [comment]
> @milan, do I still need to create a new issue for this extension and approve this for a merge as it is?

If you want this as a future feature, then yes, you should create a new issue.

**Pull request merged**
